options:
  realm:
    type: string
    defaut: EXAMPLE.COM
    description: |
      Kerberos Realm. Currently only supports a single entry.
  domain:
    type: string
    defaut: EXAMPLE.COM
    description: |
      Kerberos domain. Currently only supports a single entry.
  kdc-address:
    type: string
    description: |
      IP Address or hostname of the remote KDC or Kerberos enabled AD
      server.
  admin-server-address:
    type: string
    description: |
      IP Address or hostname of the remote admin server.
  user:
    type: string
    default: ubuntu
    description: |
      Local user to perform domain join under, defaults to ubuntu.
  principal:
    type: string
    default: host
    description: |
      principal to use when adding the server, e.g. "host/HOSTNAME.example.com"
